type: object
additionalProperties: false
required:
  - logging

properties:
  logging:
    type: object
    required:
      - log_level
    properties:
      log_level:
        type: string
        enum:
          - debug
          - info
          - warn
          - error
          - fatal
          - off

