logging:
  categories:
    default:
      level: 'debug'
    debug_log:
      level: 'info'
    app:
      level: 'debug'
    cmd:
      level: 'debug'
    diff:
      level: 'debug'
    dom:
      level: 'debug'
    tasks:
      level: 'info'
    tasks.task-runner:
      level: 'debug'
