export const NODE_TYPES = {
  1: 'ELEMENT',
  2: 'ATTRIBUTE',
  3: 'TEXT',
  4: 'CDATA_SECTION',
  7: 'PROCESSING_INSTRUCTION',
  8: 'COMMENT',
  9: 'DOCUMENT',
  10: 'DOCUMENT_TYPE',
  11: 'DOCUMENT_FRAGMENT',
}